### ISSUE TITLE
Continuous play on playlist

### ISSUE THREAD

**Issue by wklumpen** [brandoshizzle/Flask#19]
It would be good to have a setting to allow the playlist to play continuously, such as when playing house music (instead of between-scene music). Might be good to have the option toggled on the playlist itself so you can turn it on and off easily.

**Comment by brandoshizzle** [comment]
Noted! Will add to the next release.

**Comment by brandoshizzle** [comment]
@wklumpen Added this feature in latest giant commit, coming in v1.0.0!
