### ISSUE TITLE
Moving a currently playing song causes it to be stuck playing, even when esc is pressed

### ISSUE THREAD

**Issue by Kulkinz** [brandoshizzle/Flask#20]
If I am moving songs around and move a song that is currently playing, the audio is stuck playing.

Steps to replicate:

1. Play a song with a keyboard bind.
2. While its playing, CTRL + X to cut the song
3. (Optional) CTRL + V the song to somewhere else.
4. Press the esc or the original keyboard bind. The song wont stop. Pressing the key where it now is just overlaps the song.

Only way to stop it is to restart Flask. 

What I expect to occur: When song is removed as a bind for it to automatically stop if currently playing.

**Comment by brandoshizzle** [comment]
Didn't think about anyone wanting to do that haha. It's an easy fix to "stop sound when cut or deleted". Added to v1.0 to do list.

**Comment by Kulkinz** [comment]
Hahaha, Never intentional just accidental but if I had a buck for every time it occurred for me, I would have more dollars than I would like to admit.

**Comment by brandoshizzle** [comment]
Resolved in v1.0.0
