### ISSUE TITLE
Random button for playlist

### ISSUE THREAD

**Issue by Kulkinz** [brandoshizzle/Flask#21]
It'd be appreciated if there was a way to randomize the order on the playlist. That would allow for a different order of my playlist every improv rehearsal.

As it is right now, it is the same order every time, and I would prefer if there was a way to just randomize it.

**Comment by brandoshizzle** [comment]
Good suggestion! Added to the to-do list for v1.0 release coming soon :)

**Comment by brandoshizzle** [comment]
Added "shuffle playlist" feature in v1.0.0
